### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mydesireiscoma** [srcode-org/aide#2]
Do you have in plans to create some docs page?

**Comment by klintmane** [comment]
Hi @mydesireiscoma haven't had much time to work on this, but will document the current functionality today.

**Comment by klintmane** [comment]
Like I promised, the documentation is now available at the [project's site](https://srcode-org.github.io/aide/). This project is still a WIP so do not expect any new additions anytime soon, but the docs cover most of the current features.

**Comment by mydesireiscoma** [comment]
Thanks a lot my friend
